// Code generated by ent, DO NOT EDIT.

package configure

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the configure type in the database.
	Label = "configure"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// Table holds the table name of the configure in the database.
	Table = "configure"
)

// Columns holds all SQL columns for configure fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Key defines the type for the "key" enum field.
type Key string

// Key values.
const (
	KeyWorkitemConfigure Key = "workitem_configure"
)

func (k Key) String() string {
	return string(k)
}

// KeyValidator is a validator for the "key" field enum values. It is called by the builders before save.
func KeyValidator(k Key) error {
	switch k {
	case KeyWorkitemConfigure:
		return nil
	default:
		return fmt.Errorf("configure: invalid enum value for key field: %q", k)
	}
}

// OrderOption defines the ordering options for the Configure queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}
