// Code generated by ent, DO NOT EDIT.

package configure

import (
	"entgo.io/ent/dialect/sql"
	"github.com/liasica/orbit/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Configure {
	return predicate.Configure(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Configure {
	return predicate.Configure(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Configure {
	return predicate.Configure(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Configure {
	return predicate.Configure(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Configure {
	return predicate.Configure(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Configure {
	return predicate.Configure(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Configure {
	return predicate.Configure(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Configure {
	return predicate.Configure(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Configure {
	return predicate.Configure(sql.FieldLTE(FieldID, id))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v Key) predicate.Configure {
	return predicate.Configure(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v Key) predicate.Configure {
	return predicate.Configure(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...Key) predicate.Configure {
	return predicate.Configure(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...Key) predicate.Configure {
	return predicate.Configure(sql.FieldNotIn(FieldKey, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Configure) predicate.Configure {
	return predicate.Configure(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Configure) predicate.Configure {
	return predicate.Configure(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Configure) predicate.Configure {
	return predicate.Configure(sql.NotPredicates(p))
}
