// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConfigureColumns holds the columns for the "configure" table.
	ConfigureColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeEnum, Comment: "配置键", Enums: []string{"yunxiao"}},
		{Name: "data", Type: field.TypeJSON, Comment: "配置值"},
	}
	// ConfigureTable holds the schema information for the "configure" table.
	ConfigureTable = &schema.Table{
		Name:       "configure",
		Columns:    ConfigureColumns,
		PrimaryKey: []*schema.Column{ConfigureColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "configure_key",
				Unique:  true,
				Columns: []*schema.Column{ConfigureColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConfigureTable,
	}
)

func init() {
	ConfigureTable.Annotation = &entsql.Annotation{
		Table: "configure",
	}
}
