// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MessageColumns holds the columns for the "message" table.
	MessageColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "message_id", Type: field.TypeString, Unique: true, Comment: "消息ID"},
		{Name: "workitem_id", Type: field.TypeString, Nullable: true, Comment: "工作项ID"},
		{Name: "varaibales", Type: field.TypeJSON, Comment: "消息变量"},
	}
	// MessageTable holds the schema information for the "message" table.
	MessageTable = &schema.Table{
		Name:       "message",
		Columns:    MessageColumns,
		PrimaryKey: []*schema.Column{MessageColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "message_workitem_id",
				Unique:  false,
				Columns: []*schema.Column{MessageColumns[2]},
			},
		},
	}
	// RepositoryColumns holds the columns for the "repository" table.
	RepositoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "path", Type: field.TypeString, Unique: true, Comment: "仓库路径"},
	}
	// RepositoryTable holds the schema information for the "repository" table.
	RepositoryTable = &schema.Table{
		Name:       "repository",
		Columns:    RepositoryColumns,
		PrimaryKey: []*schema.Column{RepositoryColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "lark_user_id", Type: field.TypeString, Unique: true, Comment: "飞书用户ID"},
		{Name: "lark_union_id", Type: field.TypeString, Comment: "飞书 UnionId"},
		{Name: "lark_open_id", Type: field.TypeString, Comment: "飞书 OpenId"},
		{Name: "yunxiao_user_id", Type: field.TypeString, Comment: "云效用户ID"},
		{Name: "gitlab_username", Type: field.TypeString, Comment: "GitLab 用户名"},
		{Name: "gitlab_email", Type: field.TypeString, Comment: "GitLab 用户邮箱"},
		{Name: "name", Type: field.TypeString, Comment: "用户名称"},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_lark_union_id",
				Unique:  false,
				Columns: []*schema.Column{UserColumns[2]},
			},
			{
				Name:    "user_lark_open_id",
				Unique:  false,
				Columns: []*schema.Column{UserColumns[3]},
			},
			{
				Name:    "user_yunxiao_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserColumns[4]},
			},
			{
				Name:    "user_gitlab_username",
				Unique:  false,
				Columns: []*schema.Column{UserColumns[5]},
			},
			{
				Name:    "user_gitlab_email",
				Unique:  false,
				Columns: []*schema.Column{UserColumns[6]},
			},
			{
				Name:    "user_name",
				Unique:  false,
				Columns: []*schema.Column{UserColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MessageTable,
		RepositoryTable,
		UserTable,
	}
)

func init() {
	MessageTable.Annotation = &entsql.Annotation{
		Table: "message",
	}
	RepositoryTable.Annotation = &entsql.Annotation{
		Table: "repository",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
