// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bytedance/sonic"
	"github.com/liasica/orbit/ent/configure"
)

// Configure is the model entity for the Configure schema.
type Configure struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 配置键
	Key configure.Key `json:"key,omitempty"`
	// 配置值
	Data         sonic.NoCopyRawMessage `json:"data,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Configure) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case configure.FieldData:
			values[i] = new([]byte)
		case configure.FieldID:
			values[i] = new(sql.NullInt64)
		case configure.FieldKey:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Configure fields.
func (_m *Configure) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case configure.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case configure.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = configure.Key(value.String)
			}
		case configure.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Data); err != nil {
					return fmt.Errorf("unmarshal field data: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Configure.
// This includes values selected through modifiers, order, etc.
func (_m *Configure) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Configure.
// Note that you need to call Configure.Unwrap() before calling this method if this Configure
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Configure) Update() *ConfigureUpdateOne {
	return NewConfigureClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Configure entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Configure) Unwrap() *Configure {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Configure is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Configure) String() string {
	var builder strings.Builder
	builder.WriteString("Configure(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(fmt.Sprintf("%v", _m.Key))
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", _m.Data))
	builder.WriteByte(')')
	return builder.String()
}

// Configures is a parsable slice of Configure.
type Configures []*Configure
