// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bytedance/sonic"
	"github.com/liasica/orbit/ent/configure"
)

// ConfigureCreate is the builder for creating a Configure entity.
type ConfigureCreate struct {
	config
	mutation *ConfigureMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *ConfigureCreate) SetKey(v configure.Key) *ConfigureCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetData sets the "data" field.
func (_c *ConfigureCreate) SetData(v sonic.NoCopyRawMessage) *ConfigureCreate {
	_c.mutation.SetData(v)
	return _c
}

// Mutation returns the ConfigureMutation object of the builder.
func (_c *ConfigureCreate) Mutation() *ConfigureMutation {
	return _c.mutation
}

// Save creates the Configure in the database.
func (_c *ConfigureCreate) Save(ctx context.Context) (*Configure, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConfigureCreate) SaveX(ctx context.Context) *Configure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConfigureCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Configure.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := configure.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Configure.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "Configure.data"`)}
	}
	return nil
}

func (_c *ConfigureCreate) sqlSave(ctx context.Context) (*Configure, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConfigureCreate) createSpec() (*Configure, *sqlgraph.CreateSpec) {
	var (
		_node = &Configure{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(configure.Table, sqlgraph.NewFieldSpec(configure.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(configure.FieldKey, field.TypeEnum, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(configure.FieldData, field.TypeJSON, value)
		_node.Data = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Configure.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConfigureUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ConfigureCreate) OnConflict(opts ...sql.ConflictOption) *ConfigureUpsertOne {
	_c.conflict = opts
	return &ConfigureUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Configure.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConfigureCreate) OnConflictColumns(columns ...string) *ConfigureUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConfigureUpsertOne{
		create: _c,
	}
}

type (
	// ConfigureUpsertOne is the builder for "upsert"-ing
	//  one Configure node.
	ConfigureUpsertOne struct {
		create *ConfigureCreate
	}

	// ConfigureUpsert is the "OnConflict" setter.
	ConfigureUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *ConfigureUpsert) SetKey(v configure.Key) *ConfigureUpsert {
	u.Set(configure.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ConfigureUpsert) UpdateKey() *ConfigureUpsert {
	u.SetExcluded(configure.FieldKey)
	return u
}

// SetData sets the "data" field.
func (u *ConfigureUpsert) SetData(v sonic.NoCopyRawMessage) *ConfigureUpsert {
	u.Set(configure.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *ConfigureUpsert) UpdateData() *ConfigureUpsert {
	u.SetExcluded(configure.FieldData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Configure.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConfigureUpsertOne) UpdateNewValues() *ConfigureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Configure.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConfigureUpsertOne) Ignore() *ConfigureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConfigureUpsertOne) DoNothing() *ConfigureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConfigureCreate.OnConflict
// documentation for more info.
func (u *ConfigureUpsertOne) Update(set func(*ConfigureUpsert)) *ConfigureUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConfigureUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *ConfigureUpsertOne) SetKey(v configure.Key) *ConfigureUpsertOne {
	return u.Update(func(s *ConfigureUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ConfigureUpsertOne) UpdateKey() *ConfigureUpsertOne {
	return u.Update(func(s *ConfigureUpsert) {
		s.UpdateKey()
	})
}

// SetData sets the "data" field.
func (u *ConfigureUpsertOne) SetData(v sonic.NoCopyRawMessage) *ConfigureUpsertOne {
	return u.Update(func(s *ConfigureUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *ConfigureUpsertOne) UpdateData() *ConfigureUpsertOne {
	return u.Update(func(s *ConfigureUpsert) {
		s.UpdateData()
	})
}

// Exec executes the query.
func (u *ConfigureUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConfigureCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConfigureUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConfigureUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConfigureUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConfigureCreateBulk is the builder for creating many Configure entities in bulk.
type ConfigureCreateBulk struct {
	config
	err      error
	builders []*ConfigureCreate
	conflict []sql.ConflictOption
}

// Save creates the Configure entities in the database.
func (_c *ConfigureCreateBulk) Save(ctx context.Context) ([]*Configure, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Configure, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConfigureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConfigureCreateBulk) SaveX(ctx context.Context) []*Configure {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConfigureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConfigureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Configure.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConfigureUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ConfigureCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConfigureUpsertBulk {
	_c.conflict = opts
	return &ConfigureUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Configure.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConfigureCreateBulk) OnConflictColumns(columns ...string) *ConfigureUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConfigureUpsertBulk{
		create: _c,
	}
}

// ConfigureUpsertBulk is the builder for "upsert"-ing
// a bulk of Configure nodes.
type ConfigureUpsertBulk struct {
	create *ConfigureCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Configure.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConfigureUpsertBulk) UpdateNewValues() *ConfigureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Configure.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConfigureUpsertBulk) Ignore() *ConfigureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConfigureUpsertBulk) DoNothing() *ConfigureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConfigureCreateBulk.OnConflict
// documentation for more info.
func (u *ConfigureUpsertBulk) Update(set func(*ConfigureUpsert)) *ConfigureUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConfigureUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *ConfigureUpsertBulk) SetKey(v configure.Key) *ConfigureUpsertBulk {
	return u.Update(func(s *ConfigureUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ConfigureUpsertBulk) UpdateKey() *ConfigureUpsertBulk {
	return u.Update(func(s *ConfigureUpsert) {
		s.UpdateKey()
	})
}

// SetData sets the "data" field.
func (u *ConfigureUpsertBulk) SetData(v sonic.NoCopyRawMessage) *ConfigureUpsertBulk {
	return u.Update(func(s *ConfigureUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *ConfigureUpsertBulk) UpdateData() *ConfigureUpsertBulk {
	return u.Update(func(s *ConfigureUpsert) {
		s.UpdateData()
	})
}

// Exec executes the query.
func (u *ConfigureUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConfigureCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConfigureCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConfigureUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
