// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bytedance/sonic"
	"github.com/liasica/orbit/ent/configure"
	"github.com/liasica/orbit/ent/predicate"
)

// ConfigureUpdate is the builder for updating Configure entities.
type ConfigureUpdate struct {
	config
	hooks    []Hook
	mutation *ConfigureMutation
}

// Where appends a list predicates to the ConfigureUpdate builder.
func (_u *ConfigureUpdate) Where(ps ...predicate.Configure) *ConfigureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *ConfigureUpdate) SetKey(v configure.Key) *ConfigureUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ConfigureUpdate) SetNillableKey(v *configure.Key) *ConfigureUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *ConfigureUpdate) SetData(v sonic.NoCopyRawMessage) *ConfigureUpdate {
	_u.mutation.SetData(v)
	return _u
}

// AppendData appends value to the "data" field.
func (_u *ConfigureUpdate) AppendData(v sonic.NoCopyRawMessage) *ConfigureUpdate {
	_u.mutation.AppendData(v)
	return _u
}

// Mutation returns the ConfigureMutation object of the builder.
func (_u *ConfigureUpdate) Mutation() *ConfigureMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigureUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := configure.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Configure.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ConfigureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configure.Table, configure.Columns, sqlgraph.NewFieldSpec(configure.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(configure.FieldKey, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(configure.FieldData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedData(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, configure.FieldData, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigureUpdateOne is the builder for updating a single Configure entity.
type ConfigureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfigureMutation
}

// SetKey sets the "key" field.
func (_u *ConfigureUpdateOne) SetKey(v configure.Key) *ConfigureUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ConfigureUpdateOne) SetNillableKey(v *configure.Key) *ConfigureUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *ConfigureUpdateOne) SetData(v sonic.NoCopyRawMessage) *ConfigureUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// AppendData appends value to the "data" field.
func (_u *ConfigureUpdateOne) AppendData(v sonic.NoCopyRawMessage) *ConfigureUpdateOne {
	_u.mutation.AppendData(v)
	return _u
}

// Mutation returns the ConfigureMutation object of the builder.
func (_u *ConfigureUpdateOne) Mutation() *ConfigureMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConfigureUpdate builder.
func (_u *ConfigureUpdateOne) Where(ps ...predicate.Configure) *ConfigureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigureUpdateOne) Select(field string, fields ...string) *ConfigureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Configure entity.
func (_u *ConfigureUpdateOne) Save(ctx context.Context) (*Configure, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigureUpdateOne) SaveX(ctx context.Context) *Configure {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigureUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := configure.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Configure.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ConfigureUpdateOne) sqlSave(ctx context.Context) (_node *Configure, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configure.Table, configure.Columns, sqlgraph.NewFieldSpec(configure.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Configure.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configure.FieldID)
		for _, f := range fields {
			if !configure.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != configure.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(configure.FieldKey, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(configure.FieldData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedData(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, configure.FieldData, value)
		})
	}
	_node = &Configure{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
