// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bytedance/sonic"
	"github.com/liasica/orbit/ent/message"
	"github.com/liasica/orbit/ent/predicate"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MessageUpdate) SetMessageID(v string) *MessageUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableMessageID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MessageUpdate) SetType(v message.Type) *MessageUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableType(v *message.Type) *MessageUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetWorkitemID sets the "workitem_id" field.
func (_u *MessageUpdate) SetWorkitemID(v string) *MessageUpdate {
	_u.mutation.SetWorkitemID(v)
	return _u
}

// SetNillableWorkitemID sets the "workitem_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableWorkitemID(v *string) *MessageUpdate {
	if v != nil {
		_u.SetWorkitemID(*v)
	}
	return _u
}

// ClearWorkitemID clears the value of the "workitem_id" field.
func (_u *MessageUpdate) ClearWorkitemID() *MessageUpdate {
	_u.mutation.ClearWorkitemID()
	return _u
}

// SetVaraibales sets the "varaibales" field.
func (_u *MessageUpdate) SetVaraibales(v sonic.NoCopyRawMessage) *MessageUpdate {
	_u.mutation.SetVaraibales(v)
	return _u
}

// AppendVaraibales appends value to the "varaibales" field.
func (_u *MessageUpdate) AppendVaraibales(v sonic.NoCopyRawMessage) *MessageUpdate {
	_u.mutation.AppendVaraibales(v)
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := message.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Message.type": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(message.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(message.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.WorkitemID(); ok {
		_spec.SetField(message.FieldWorkitemID, field.TypeString, value)
	}
	if _u.mutation.WorkitemIDCleared() {
		_spec.ClearField(message.FieldWorkitemID, field.TypeString)
	}
	if value, ok := _u.mutation.Varaibales(); ok {
		_spec.SetField(message.FieldVaraibales, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVaraibales(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldVaraibales, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetMessageID sets the "message_id" field.
func (_u *MessageUpdateOne) SetMessageID(v string) *MessageUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableMessageID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MessageUpdateOne) SetType(v message.Type) *MessageUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableType(v *message.Type) *MessageUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetWorkitemID sets the "workitem_id" field.
func (_u *MessageUpdateOne) SetWorkitemID(v string) *MessageUpdateOne {
	_u.mutation.SetWorkitemID(v)
	return _u
}

// SetNillableWorkitemID sets the "workitem_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableWorkitemID(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetWorkitemID(*v)
	}
	return _u
}

// ClearWorkitemID clears the value of the "workitem_id" field.
func (_u *MessageUpdateOne) ClearWorkitemID() *MessageUpdateOne {
	_u.mutation.ClearWorkitemID()
	return _u
}

// SetVaraibales sets the "varaibales" field.
func (_u *MessageUpdateOne) SetVaraibales(v sonic.NoCopyRawMessage) *MessageUpdateOne {
	_u.mutation.SetVaraibales(v)
	return _u
}

// AppendVaraibales appends value to the "varaibales" field.
func (_u *MessageUpdateOne) AppendVaraibales(v sonic.NoCopyRawMessage) *MessageUpdateOne {
	_u.mutation.AppendVaraibales(v)
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := message.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Message.type": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(message.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(message.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.WorkitemID(); ok {
		_spec.SetField(message.FieldWorkitemID, field.TypeString, value)
	}
	if _u.mutation.WorkitemIDCleared() {
		_spec.ClearField(message.FieldWorkitemID, field.TypeString)
	}
	if value, ok := _u.mutation.Varaibales(); ok {
		_spec.SetField(message.FieldVaraibales, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVaraibales(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldVaraibales, value)
		})
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
