// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/liasica/orbit/ent/predicate"
	"github.com/liasica/orbit/ent/user"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeUser = "User"
)

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op              Op
	typ             string
	id              *int
	lark_user_id    *string
	lark_union_id   *string
	lark_open_id    *string
	yunxiao_user_id *string
	gitlab_username *string
	gitlab_email    *string
	name            *string
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*User, error)
	predicates      []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetLarkUserID sets the "lark_user_id" field.
func (m *UserMutation) SetLarkUserID(s string) {
	m.lark_user_id = &s
}

// LarkUserID returns the value of the "lark_user_id" field in the mutation.
func (m *UserMutation) LarkUserID() (r string, exists bool) {
	v := m.lark_user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldLarkUserID returns the old "lark_user_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldLarkUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLarkUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLarkUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLarkUserID: %w", err)
	}
	return oldValue.LarkUserID, nil
}

// ResetLarkUserID resets all changes to the "lark_user_id" field.
func (m *UserMutation) ResetLarkUserID() {
	m.lark_user_id = nil
}

// SetLarkUnionID sets the "lark_union_id" field.
func (m *UserMutation) SetLarkUnionID(s string) {
	m.lark_union_id = &s
}

// LarkUnionID returns the value of the "lark_union_id" field in the mutation.
func (m *UserMutation) LarkUnionID() (r string, exists bool) {
	v := m.lark_union_id
	if v == nil {
		return
	}
	return *v, true
}

// OldLarkUnionID returns the old "lark_union_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldLarkUnionID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLarkUnionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLarkUnionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLarkUnionID: %w", err)
	}
	return oldValue.LarkUnionID, nil
}

// ResetLarkUnionID resets all changes to the "lark_union_id" field.
func (m *UserMutation) ResetLarkUnionID() {
	m.lark_union_id = nil
}

// SetLarkOpenID sets the "lark_open_id" field.
func (m *UserMutation) SetLarkOpenID(s string) {
	m.lark_open_id = &s
}

// LarkOpenID returns the value of the "lark_open_id" field in the mutation.
func (m *UserMutation) LarkOpenID() (r string, exists bool) {
	v := m.lark_open_id
	if v == nil {
		return
	}
	return *v, true
}

// OldLarkOpenID returns the old "lark_open_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldLarkOpenID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLarkOpenID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLarkOpenID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLarkOpenID: %w", err)
	}
	return oldValue.LarkOpenID, nil
}

// ResetLarkOpenID resets all changes to the "lark_open_id" field.
func (m *UserMutation) ResetLarkOpenID() {
	m.lark_open_id = nil
}

// SetYunxiaoUserID sets the "yunxiao_user_id" field.
func (m *UserMutation) SetYunxiaoUserID(s string) {
	m.yunxiao_user_id = &s
}

// YunxiaoUserID returns the value of the "yunxiao_user_id" field in the mutation.
func (m *UserMutation) YunxiaoUserID() (r string, exists bool) {
	v := m.yunxiao_user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldYunxiaoUserID returns the old "yunxiao_user_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldYunxiaoUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldYunxiaoUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldYunxiaoUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldYunxiaoUserID: %w", err)
	}
	return oldValue.YunxiaoUserID, nil
}

// ResetYunxiaoUserID resets all changes to the "yunxiao_user_id" field.
func (m *UserMutation) ResetYunxiaoUserID() {
	m.yunxiao_user_id = nil
}

// SetGitlabUsername sets the "gitlab_username" field.
func (m *UserMutation) SetGitlabUsername(s string) {
	m.gitlab_username = &s
}

// GitlabUsername returns the value of the "gitlab_username" field in the mutation.
func (m *UserMutation) GitlabUsername() (r string, exists bool) {
	v := m.gitlab_username
	if v == nil {
		return
	}
	return *v, true
}

// OldGitlabUsername returns the old "gitlab_username" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldGitlabUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGitlabUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGitlabUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGitlabUsername: %w", err)
	}
	return oldValue.GitlabUsername, nil
}

// ResetGitlabUsername resets all changes to the "gitlab_username" field.
func (m *UserMutation) ResetGitlabUsername() {
	m.gitlab_username = nil
}

// SetGitlabEmail sets the "gitlab_email" field.
func (m *UserMutation) SetGitlabEmail(s string) {
	m.gitlab_email = &s
}

// GitlabEmail returns the value of the "gitlab_email" field in the mutation.
func (m *UserMutation) GitlabEmail() (r string, exists bool) {
	v := m.gitlab_email
	if v == nil {
		return
	}
	return *v, true
}

// OldGitlabEmail returns the old "gitlab_email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldGitlabEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGitlabEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGitlabEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGitlabEmail: %w", err)
	}
	return oldValue.GitlabEmail, nil
}

// ResetGitlabEmail resets all changes to the "gitlab_email" field.
func (m *UserMutation) ResetGitlabEmail() {
	m.gitlab_email = nil
}

// SetName sets the "name" field.
func (m *UserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *UserMutation) ResetName() {
	m.name = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.lark_user_id != nil {
		fields = append(fields, user.FieldLarkUserID)
	}
	if m.lark_union_id != nil {
		fields = append(fields, user.FieldLarkUnionID)
	}
	if m.lark_open_id != nil {
		fields = append(fields, user.FieldLarkOpenID)
	}
	if m.yunxiao_user_id != nil {
		fields = append(fields, user.FieldYunxiaoUserID)
	}
	if m.gitlab_username != nil {
		fields = append(fields, user.FieldGitlabUsername)
	}
	if m.gitlab_email != nil {
		fields = append(fields, user.FieldGitlabEmail)
	}
	if m.name != nil {
		fields = append(fields, user.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldLarkUserID:
		return m.LarkUserID()
	case user.FieldLarkUnionID:
		return m.LarkUnionID()
	case user.FieldLarkOpenID:
		return m.LarkOpenID()
	case user.FieldYunxiaoUserID:
		return m.YunxiaoUserID()
	case user.FieldGitlabUsername:
		return m.GitlabUsername()
	case user.FieldGitlabEmail:
		return m.GitlabEmail()
	case user.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldLarkUserID:
		return m.OldLarkUserID(ctx)
	case user.FieldLarkUnionID:
		return m.OldLarkUnionID(ctx)
	case user.FieldLarkOpenID:
		return m.OldLarkOpenID(ctx)
	case user.FieldYunxiaoUserID:
		return m.OldYunxiaoUserID(ctx)
	case user.FieldGitlabUsername:
		return m.OldGitlabUsername(ctx)
	case user.FieldGitlabEmail:
		return m.OldGitlabEmail(ctx)
	case user.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldLarkUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLarkUserID(v)
		return nil
	case user.FieldLarkUnionID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLarkUnionID(v)
		return nil
	case user.FieldLarkOpenID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLarkOpenID(v)
		return nil
	case user.FieldYunxiaoUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetYunxiaoUserID(v)
		return nil
	case user.FieldGitlabUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGitlabUsername(v)
		return nil
	case user.FieldGitlabEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGitlabEmail(v)
		return nil
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldLarkUserID:
		m.ResetLarkUserID()
		return nil
	case user.FieldLarkUnionID:
		m.ResetLarkUnionID()
		return nil
	case user.FieldLarkOpenID:
		m.ResetLarkOpenID()
		return nil
	case user.FieldYunxiaoUserID:
		m.ResetYunxiaoUserID()
		return nil
	case user.FieldGitlabUsername:
		m.ResetGitlabUsername()
		return nil
	case user.FieldGitlabEmail:
		m.ResetGitlabEmail()
		return nil
	case user.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown User edge %s", name)
}
