// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bytedance/sonic"
	"github.com/liasica/orbit/ent/configure"
	"github.com/liasica/orbit/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeConfigure = "Configure"
)

// ConfigureMutation represents an operation that mutates the Configure nodes in the graph.
type ConfigureMutation struct {
	config
	op            Op
	typ           string
	id            *int
	key           *configure.Key
	data          *sonic.NoCopyRawMessage
	appenddata    sonic.NoCopyRawMessage
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Configure, error)
	predicates    []predicate.Configure
}

var _ ent.Mutation = (*ConfigureMutation)(nil)

// configureOption allows management of the mutation configuration using functional options.
type configureOption func(*ConfigureMutation)

// newConfigureMutation creates new mutation for the Configure entity.
func newConfigureMutation(c config, op Op, opts ...configureOption) *ConfigureMutation {
	m := &ConfigureMutation{
		config:        c,
		op:            op,
		typ:           TypeConfigure,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withConfigureID sets the ID field of the mutation.
func withConfigureID(id int) configureOption {
	return func(m *ConfigureMutation) {
		var (
			err   error
			once  sync.Once
			value *Configure
		)
		m.oldValue = func(ctx context.Context) (*Configure, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Configure.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withConfigure sets the old Configure of the mutation.
func withConfigure(node *Configure) configureOption {
	return func(m *ConfigureMutation) {
		m.oldValue = func(context.Context) (*Configure, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ConfigureMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ConfigureMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ConfigureMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ConfigureMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Configure.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetKey sets the "key" field.
func (m *ConfigureMutation) SetKey(c configure.Key) {
	m.key = &c
}

// Key returns the value of the "key" field in the mutation.
func (m *ConfigureMutation) Key() (r configure.Key, exists bool) {
	v := m.key
	if v == nil {
		return
	}
	return *v, true
}

// OldKey returns the old "key" field's value of the Configure entity.
// If the Configure object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConfigureMutation) OldKey(ctx context.Context) (v configure.Key, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKey: %w", err)
	}
	return oldValue.Key, nil
}

// ResetKey resets all changes to the "key" field.
func (m *ConfigureMutation) ResetKey() {
	m.key = nil
}

// SetData sets the "data" field.
func (m *ConfigureMutation) SetData(scrm sonic.NoCopyRawMessage) {
	m.data = &scrm
	m.appenddata = nil
}

// Data returns the value of the "data" field in the mutation.
func (m *ConfigureMutation) Data() (r sonic.NoCopyRawMessage, exists bool) {
	v := m.data
	if v == nil {
		return
	}
	return *v, true
}

// OldData returns the old "data" field's value of the Configure entity.
// If the Configure object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConfigureMutation) OldData(ctx context.Context) (v sonic.NoCopyRawMessage, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldData is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldData requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldData: %w", err)
	}
	return oldValue.Data, nil
}

// AppendData adds scrm to the "data" field.
func (m *ConfigureMutation) AppendData(scrm sonic.NoCopyRawMessage) {
	m.appenddata = append(m.appenddata, scrm...)
}

// AppendedData returns the list of values that were appended to the "data" field in this mutation.
func (m *ConfigureMutation) AppendedData() (sonic.NoCopyRawMessage, bool) {
	if len(m.appenddata) == 0 {
		return nil, false
	}
	return m.appenddata, true
}

// ResetData resets all changes to the "data" field.
func (m *ConfigureMutation) ResetData() {
	m.data = nil
	m.appenddata = nil
}

// Where appends a list predicates to the ConfigureMutation builder.
func (m *ConfigureMutation) Where(ps ...predicate.Configure) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ConfigureMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ConfigureMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Configure, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ConfigureMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ConfigureMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Configure).
func (m *ConfigureMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ConfigureMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.key != nil {
		fields = append(fields, configure.FieldKey)
	}
	if m.data != nil {
		fields = append(fields, configure.FieldData)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ConfigureMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case configure.FieldKey:
		return m.Key()
	case configure.FieldData:
		return m.Data()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ConfigureMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case configure.FieldKey:
		return m.OldKey(ctx)
	case configure.FieldData:
		return m.OldData(ctx)
	}
	return nil, fmt.Errorf("unknown Configure field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ConfigureMutation) SetField(name string, value ent.Value) error {
	switch name {
	case configure.FieldKey:
		v, ok := value.(configure.Key)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKey(v)
		return nil
	case configure.FieldData:
		v, ok := value.(sonic.NoCopyRawMessage)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetData(v)
		return nil
	}
	return fmt.Errorf("unknown Configure field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ConfigureMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ConfigureMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ConfigureMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Configure numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ConfigureMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ConfigureMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ConfigureMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Configure nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ConfigureMutation) ResetField(name string) error {
	switch name {
	case configure.FieldKey:
		m.ResetKey()
		return nil
	case configure.FieldData:
		m.ResetData()
		return nil
	}
	return fmt.Errorf("unknown Configure field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ConfigureMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ConfigureMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ConfigureMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ConfigureMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ConfigureMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ConfigureMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ConfigureMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Configure unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ConfigureMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Configure edge %s", name)
}
