// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/liasica/orbit/ent/predicate"
	"github.com/liasica/orbit/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLarkUserID sets the "lark_user_id" field.
func (_u *UserUpdate) SetLarkUserID(v string) *UserUpdate {
	_u.mutation.SetLarkUserID(v)
	return _u
}

// SetNillableLarkUserID sets the "lark_user_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLarkUserID(v *string) *UserUpdate {
	if v != nil {
		_u.SetLarkUserID(*v)
	}
	return _u
}

// SetLarkUnionID sets the "lark_union_id" field.
func (_u *UserUpdate) SetLarkUnionID(v string) *UserUpdate {
	_u.mutation.SetLarkUnionID(v)
	return _u
}

// SetNillableLarkUnionID sets the "lark_union_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLarkUnionID(v *string) *UserUpdate {
	if v != nil {
		_u.SetLarkUnionID(*v)
	}
	return _u
}

// SetLarkOpenID sets the "lark_open_id" field.
func (_u *UserUpdate) SetLarkOpenID(v string) *UserUpdate {
	_u.mutation.SetLarkOpenID(v)
	return _u
}

// SetNillableLarkOpenID sets the "lark_open_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLarkOpenID(v *string) *UserUpdate {
	if v != nil {
		_u.SetLarkOpenID(*v)
	}
	return _u
}

// SetYunxiaoUserID sets the "yunxiao_user_id" field.
func (_u *UserUpdate) SetYunxiaoUserID(v string) *UserUpdate {
	_u.mutation.SetYunxiaoUserID(v)
	return _u
}

// SetNillableYunxiaoUserID sets the "yunxiao_user_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableYunxiaoUserID(v *string) *UserUpdate {
	if v != nil {
		_u.SetYunxiaoUserID(*v)
	}
	return _u
}

// SetGitlabUsername sets the "gitlab_username" field.
func (_u *UserUpdate) SetGitlabUsername(v string) *UserUpdate {
	_u.mutation.SetGitlabUsername(v)
	return _u
}

// SetNillableGitlabUsername sets the "gitlab_username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGitlabUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetGitlabUsername(*v)
	}
	return _u
}

// SetGitlabEmail sets the "gitlab_email" field.
func (_u *UserUpdate) SetGitlabEmail(v string) *UserUpdate {
	_u.mutation.SetGitlabEmail(v)
	return _u
}

// SetNillableGitlabEmail sets the "gitlab_email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGitlabEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetGitlabEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LarkUserID(); ok {
		_spec.SetField(user.FieldLarkUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LarkUnionID(); ok {
		_spec.SetField(user.FieldLarkUnionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LarkOpenID(); ok {
		_spec.SetField(user.FieldLarkOpenID, field.TypeString, value)
	}
	if value, ok := _u.mutation.YunxiaoUserID(); ok {
		_spec.SetField(user.FieldYunxiaoUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitlabUsername(); ok {
		_spec.SetField(user.FieldGitlabUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitlabEmail(); ok {
		_spec.SetField(user.FieldGitlabEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetLarkUserID sets the "lark_user_id" field.
func (_u *UserUpdateOne) SetLarkUserID(v string) *UserUpdateOne {
	_u.mutation.SetLarkUserID(v)
	return _u
}

// SetNillableLarkUserID sets the "lark_user_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLarkUserID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLarkUserID(*v)
	}
	return _u
}

// SetLarkUnionID sets the "lark_union_id" field.
func (_u *UserUpdateOne) SetLarkUnionID(v string) *UserUpdateOne {
	_u.mutation.SetLarkUnionID(v)
	return _u
}

// SetNillableLarkUnionID sets the "lark_union_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLarkUnionID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLarkUnionID(*v)
	}
	return _u
}

// SetLarkOpenID sets the "lark_open_id" field.
func (_u *UserUpdateOne) SetLarkOpenID(v string) *UserUpdateOne {
	_u.mutation.SetLarkOpenID(v)
	return _u
}

// SetNillableLarkOpenID sets the "lark_open_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLarkOpenID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLarkOpenID(*v)
	}
	return _u
}

// SetYunxiaoUserID sets the "yunxiao_user_id" field.
func (_u *UserUpdateOne) SetYunxiaoUserID(v string) *UserUpdateOne {
	_u.mutation.SetYunxiaoUserID(v)
	return _u
}

// SetNillableYunxiaoUserID sets the "yunxiao_user_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableYunxiaoUserID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetYunxiaoUserID(*v)
	}
	return _u
}

// SetGitlabUsername sets the "gitlab_username" field.
func (_u *UserUpdateOne) SetGitlabUsername(v string) *UserUpdateOne {
	_u.mutation.SetGitlabUsername(v)
	return _u
}

// SetNillableGitlabUsername sets the "gitlab_username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGitlabUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGitlabUsername(*v)
	}
	return _u
}

// SetGitlabEmail sets the "gitlab_email" field.
func (_u *UserUpdateOne) SetGitlabEmail(v string) *UserUpdateOne {
	_u.mutation.SetGitlabEmail(v)
	return _u
}

// SetNillableGitlabEmail sets the "gitlab_email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGitlabEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGitlabEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LarkUserID(); ok {
		_spec.SetField(user.FieldLarkUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LarkUnionID(); ok {
		_spec.SetField(user.FieldLarkUnionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LarkOpenID(); ok {
		_spec.SetField(user.FieldLarkOpenID, field.TypeString, value)
	}
	if value, ok := _u.mutation.YunxiaoUserID(); ok {
		_spec.SetField(user.FieldYunxiaoUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitlabUsername(); ok {
		_spec.SetField(user.FieldGitlabUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitlabEmail(); ok {
		_spec.SetField(user.FieldGitlabEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
