// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/liasica/orbit/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 飞书用户ID
	LarkUserID string `json:"lark_user_id,omitempty"`
	// 飞书 UnionId
	LarkUnionID string `json:"lark_union_id,omitempty"`
	// 飞书 OpenId
	LarkOpenID string `json:"lark_open_id,omitempty"`
	// 云效用户ID
	YunxiaoUserID string `json:"yunxiao_user_id,omitempty"`
	// GitLab 用户名
	GitlabUsername string `json:"gitlab_username,omitempty"`
	// GitLab 用户邮箱
	GitlabEmail string `json:"gitlab_email,omitempty"`
	// 用户名称
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldLarkUserID, user.FieldLarkUnionID, user.FieldLarkOpenID, user.FieldYunxiaoUserID, user.FieldGitlabUsername, user.FieldGitlabEmail, user.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldLarkUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lark_user_id", values[i])
			} else if value.Valid {
				_m.LarkUserID = value.String
			}
		case user.FieldLarkUnionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lark_union_id", values[i])
			} else if value.Valid {
				_m.LarkUnionID = value.String
			}
		case user.FieldLarkOpenID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lark_open_id", values[i])
			} else if value.Valid {
				_m.LarkOpenID = value.String
			}
		case user.FieldYunxiaoUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field yunxiao_user_id", values[i])
			} else if value.Valid {
				_m.YunxiaoUserID = value.String
			}
		case user.FieldGitlabUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gitlab_username", values[i])
			} else if value.Valid {
				_m.GitlabUsername = value.String
			}
		case user.FieldGitlabEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gitlab_email", values[i])
			} else if value.Valid {
				_m.GitlabEmail = value.String
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("lark_user_id=")
	builder.WriteString(_m.LarkUserID)
	builder.WriteString(", ")
	builder.WriteString("lark_union_id=")
	builder.WriteString(_m.LarkUnionID)
	builder.WriteString(", ")
	builder.WriteString("lark_open_id=")
	builder.WriteString(_m.LarkOpenID)
	builder.WriteString(", ")
	builder.WriteString("yunxiao_user_id=")
	builder.WriteString(_m.YunxiaoUserID)
	builder.WriteString(", ")
	builder.WriteString("gitlab_username=")
	builder.WriteString(_m.GitlabUsername)
	builder.WriteString(", ")
	builder.WriteString("gitlab_email=")
	builder.WriteString(_m.GitlabEmail)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
