// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/liasica/orbit/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLarkUserID sets the "lark_user_id" field.
func (_c *UserCreate) SetLarkUserID(v string) *UserCreate {
	_c.mutation.SetLarkUserID(v)
	return _c
}

// SetLarkUnionID sets the "lark_union_id" field.
func (_c *UserCreate) SetLarkUnionID(v string) *UserCreate {
	_c.mutation.SetLarkUnionID(v)
	return _c
}

// SetLarkOpenID sets the "lark_open_id" field.
func (_c *UserCreate) SetLarkOpenID(v string) *UserCreate {
	_c.mutation.SetLarkOpenID(v)
	return _c
}

// SetYunxiaoUserID sets the "yunxiao_user_id" field.
func (_c *UserCreate) SetYunxiaoUserID(v string) *UserCreate {
	_c.mutation.SetYunxiaoUserID(v)
	return _c
}

// SetGitlabUsername sets the "gitlab_username" field.
func (_c *UserCreate) SetGitlabUsername(v string) *UserCreate {
	_c.mutation.SetGitlabUsername(v)
	return _c
}

// SetGitlabEmail sets the "gitlab_email" field.
func (_c *UserCreate) SetGitlabEmail(v string) *UserCreate {
	_c.mutation.SetGitlabEmail(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.LarkUserID(); !ok {
		return &ValidationError{Name: "lark_user_id", err: errors.New(`ent: missing required field "User.lark_user_id"`)}
	}
	if _, ok := _c.mutation.LarkUnionID(); !ok {
		return &ValidationError{Name: "lark_union_id", err: errors.New(`ent: missing required field "User.lark_union_id"`)}
	}
	if _, ok := _c.mutation.LarkOpenID(); !ok {
		return &ValidationError{Name: "lark_open_id", err: errors.New(`ent: missing required field "User.lark_open_id"`)}
	}
	if _, ok := _c.mutation.YunxiaoUserID(); !ok {
		return &ValidationError{Name: "yunxiao_user_id", err: errors.New(`ent: missing required field "User.yunxiao_user_id"`)}
	}
	if _, ok := _c.mutation.GitlabUsername(); !ok {
		return &ValidationError{Name: "gitlab_username", err: errors.New(`ent: missing required field "User.gitlab_username"`)}
	}
	if _, ok := _c.mutation.GitlabEmail(); !ok {
		return &ValidationError{Name: "gitlab_email", err: errors.New(`ent: missing required field "User.gitlab_email"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.LarkUserID(); ok {
		_spec.SetField(user.FieldLarkUserID, field.TypeString, value)
		_node.LarkUserID = value
	}
	if value, ok := _c.mutation.LarkUnionID(); ok {
		_spec.SetField(user.FieldLarkUnionID, field.TypeString, value)
		_node.LarkUnionID = value
	}
	if value, ok := _c.mutation.LarkOpenID(); ok {
		_spec.SetField(user.FieldLarkOpenID, field.TypeString, value)
		_node.LarkOpenID = value
	}
	if value, ok := _c.mutation.YunxiaoUserID(); ok {
		_spec.SetField(user.FieldYunxiaoUserID, field.TypeString, value)
		_node.YunxiaoUserID = value
	}
	if value, ok := _c.mutation.GitlabUsername(); ok {
		_spec.SetField(user.FieldGitlabUsername, field.TypeString, value)
		_node.GitlabUsername = value
	}
	if value, ok := _c.mutation.GitlabEmail(); ok {
		_spec.SetField(user.FieldGitlabEmail, field.TypeString, value)
		_node.GitlabEmail = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.Create().
//		SetLarkUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetLarkUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreate) OnConflict(opts ...sql.ConflictOption) *UserUpsertOne {
	_c.conflict = opts
	return &UserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreate) OnConflictColumns(columns ...string) *UserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertOne{
		create: _c,
	}
}

type (
	// UserUpsertOne is the builder for "upsert"-ing
	//  one User node.
	UserUpsertOne struct {
		create *UserCreate
	}

	// UserUpsert is the "OnConflict" setter.
	UserUpsert struct {
		*sql.UpdateSet
	}
)

// SetLarkUserID sets the "lark_user_id" field.
func (u *UserUpsert) SetLarkUserID(v string) *UserUpsert {
	u.Set(user.FieldLarkUserID, v)
	return u
}

// UpdateLarkUserID sets the "lark_user_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateLarkUserID() *UserUpsert {
	u.SetExcluded(user.FieldLarkUserID)
	return u
}

// SetLarkUnionID sets the "lark_union_id" field.
func (u *UserUpsert) SetLarkUnionID(v string) *UserUpsert {
	u.Set(user.FieldLarkUnionID, v)
	return u
}

// UpdateLarkUnionID sets the "lark_union_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateLarkUnionID() *UserUpsert {
	u.SetExcluded(user.FieldLarkUnionID)
	return u
}

// SetLarkOpenID sets the "lark_open_id" field.
func (u *UserUpsert) SetLarkOpenID(v string) *UserUpsert {
	u.Set(user.FieldLarkOpenID, v)
	return u
}

// UpdateLarkOpenID sets the "lark_open_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateLarkOpenID() *UserUpsert {
	u.SetExcluded(user.FieldLarkOpenID)
	return u
}

// SetYunxiaoUserID sets the "yunxiao_user_id" field.
func (u *UserUpsert) SetYunxiaoUserID(v string) *UserUpsert {
	u.Set(user.FieldYunxiaoUserID, v)
	return u
}

// UpdateYunxiaoUserID sets the "yunxiao_user_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateYunxiaoUserID() *UserUpsert {
	u.SetExcluded(user.FieldYunxiaoUserID)
	return u
}

// SetGitlabUsername sets the "gitlab_username" field.
func (u *UserUpsert) SetGitlabUsername(v string) *UserUpsert {
	u.Set(user.FieldGitlabUsername, v)
	return u
}

// UpdateGitlabUsername sets the "gitlab_username" field to the value that was provided on create.
func (u *UserUpsert) UpdateGitlabUsername() *UserUpsert {
	u.SetExcluded(user.FieldGitlabUsername)
	return u
}

// SetGitlabEmail sets the "gitlab_email" field.
func (u *UserUpsert) SetGitlabEmail(v string) *UserUpsert {
	u.Set(user.FieldGitlabEmail, v)
	return u
}

// UpdateGitlabEmail sets the "gitlab_email" field to the value that was provided on create.
func (u *UserUpsert) UpdateGitlabEmail() *UserUpsert {
	u.SetExcluded(user.FieldGitlabEmail)
	return u
}

// SetName sets the "name" field.
func (u *UserUpsert) SetName(v string) *UserUpsert {
	u.Set(user.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsert) UpdateName() *UserUpsert {
	u.SetExcluded(user.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUpsertOne) UpdateNewValues() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserUpsertOne) Ignore() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertOne) DoNothing() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreate.OnConflict
// documentation for more info.
func (u *UserUpsertOne) Update(set func(*UserUpsert)) *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetLarkUserID sets the "lark_user_id" field.
func (u *UserUpsertOne) SetLarkUserID(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetLarkUserID(v)
	})
}

// UpdateLarkUserID sets the "lark_user_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateLarkUserID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLarkUserID()
	})
}

// SetLarkUnionID sets the "lark_union_id" field.
func (u *UserUpsertOne) SetLarkUnionID(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetLarkUnionID(v)
	})
}

// UpdateLarkUnionID sets the "lark_union_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateLarkUnionID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLarkUnionID()
	})
}

// SetLarkOpenID sets the "lark_open_id" field.
func (u *UserUpsertOne) SetLarkOpenID(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetLarkOpenID(v)
	})
}

// UpdateLarkOpenID sets the "lark_open_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateLarkOpenID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLarkOpenID()
	})
}

// SetYunxiaoUserID sets the "yunxiao_user_id" field.
func (u *UserUpsertOne) SetYunxiaoUserID(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetYunxiaoUserID(v)
	})
}

// UpdateYunxiaoUserID sets the "yunxiao_user_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateYunxiaoUserID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateYunxiaoUserID()
	})
}

// SetGitlabUsername sets the "gitlab_username" field.
func (u *UserUpsertOne) SetGitlabUsername(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetGitlabUsername(v)
	})
}

// UpdateGitlabUsername sets the "gitlab_username" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateGitlabUsername() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateGitlabUsername()
	})
}

// SetGitlabEmail sets the "gitlab_email" field.
func (u *UserUpsertOne) SetGitlabEmail(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetGitlabEmail(v)
	})
}

// UpdateGitlabEmail sets the "gitlab_email" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateGitlabEmail() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateGitlabEmail()
	})
}

// SetName sets the "name" field.
func (u *UserUpsertOne) SetName(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateName() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *UserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
	conflict []sql.ConflictOption
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetLarkUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserUpsertBulk {
	_c.conflict = opts
	return &UserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreateBulk) OnConflictColumns(columns ...string) *UserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertBulk{
		create: _c,
	}
}

// UserUpsertBulk is the builder for "upsert"-ing
// a bulk of User nodes.
type UserUpsertBulk struct {
	create *UserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUpsertBulk) UpdateNewValues() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserUpsertBulk) Ignore() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertBulk) DoNothing() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreateBulk.OnConflict
// documentation for more info.
func (u *UserUpsertBulk) Update(set func(*UserUpsert)) *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetLarkUserID sets the "lark_user_id" field.
func (u *UserUpsertBulk) SetLarkUserID(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetLarkUserID(v)
	})
}

// UpdateLarkUserID sets the "lark_user_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateLarkUserID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLarkUserID()
	})
}

// SetLarkUnionID sets the "lark_union_id" field.
func (u *UserUpsertBulk) SetLarkUnionID(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetLarkUnionID(v)
	})
}

// UpdateLarkUnionID sets the "lark_union_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateLarkUnionID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLarkUnionID()
	})
}

// SetLarkOpenID sets the "lark_open_id" field.
func (u *UserUpsertBulk) SetLarkOpenID(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetLarkOpenID(v)
	})
}

// UpdateLarkOpenID sets the "lark_open_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateLarkOpenID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLarkOpenID()
	})
}

// SetYunxiaoUserID sets the "yunxiao_user_id" field.
func (u *UserUpsertBulk) SetYunxiaoUserID(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetYunxiaoUserID(v)
	})
}

// UpdateYunxiaoUserID sets the "yunxiao_user_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateYunxiaoUserID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateYunxiaoUserID()
	})
}

// SetGitlabUsername sets the "gitlab_username" field.
func (u *UserUpsertBulk) SetGitlabUsername(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetGitlabUsername(v)
	})
}

// UpdateGitlabUsername sets the "gitlab_username" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateGitlabUsername() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateGitlabUsername()
	})
}

// SetGitlabEmail sets the "gitlab_email" field.
func (u *UserUpsertBulk) SetGitlabEmail(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetGitlabEmail(v)
	})
}

// UpdateGitlabEmail sets the "gitlab_email" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateGitlabEmail() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateGitlabEmail()
	})
}

// SetName sets the "name" field.
func (u *UserUpsertBulk) SetName(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateName() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *UserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
