// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/liasica/orbit/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldMessageID, v))
}

// WorkitemID applies equality check predicate on the "workitem_id" field. It's identical to WorkitemIDEQ.
func WorkitemID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldWorkitemID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldMessageID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldType, vs...))
}

// WorkitemIDEQ applies the EQ predicate on the "workitem_id" field.
func WorkitemIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldWorkitemID, v))
}

// WorkitemIDNEQ applies the NEQ predicate on the "workitem_id" field.
func WorkitemIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldWorkitemID, v))
}

// WorkitemIDIn applies the In predicate on the "workitem_id" field.
func WorkitemIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldWorkitemID, vs...))
}

// WorkitemIDNotIn applies the NotIn predicate on the "workitem_id" field.
func WorkitemIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldWorkitemID, vs...))
}

// WorkitemIDGT applies the GT predicate on the "workitem_id" field.
func WorkitemIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldWorkitemID, v))
}

// WorkitemIDGTE applies the GTE predicate on the "workitem_id" field.
func WorkitemIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldWorkitemID, v))
}

// WorkitemIDLT applies the LT predicate on the "workitem_id" field.
func WorkitemIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldWorkitemID, v))
}

// WorkitemIDLTE applies the LTE predicate on the "workitem_id" field.
func WorkitemIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldWorkitemID, v))
}

// WorkitemIDContains applies the Contains predicate on the "workitem_id" field.
func WorkitemIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldWorkitemID, v))
}

// WorkitemIDHasPrefix applies the HasPrefix predicate on the "workitem_id" field.
func WorkitemIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldWorkitemID, v))
}

// WorkitemIDHasSuffix applies the HasSuffix predicate on the "workitem_id" field.
func WorkitemIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldWorkitemID, v))
}

// WorkitemIDIsNil applies the IsNil predicate on the "workitem_id" field.
func WorkitemIDIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldWorkitemID))
}

// WorkitemIDNotNil applies the NotNil predicate on the "workitem_id" field.
func WorkitemIDNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldWorkitemID))
}

// WorkitemIDEqualFold applies the EqualFold predicate on the "workitem_id" field.
func WorkitemIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldWorkitemID, v))
}

// WorkitemIDContainsFold applies the ContainsFold predicate on the "workitem_id" field.
func WorkitemIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldWorkitemID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
