// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLarkUserID holds the string denoting the lark_user_id field in the database.
	FieldLarkUserID = "lark_user_id"
	// FieldLarkUnionID holds the string denoting the lark_union_id field in the database.
	FieldLarkUnionID = "lark_union_id"
	// FieldLarkOpenID holds the string denoting the lark_open_id field in the database.
	FieldLarkOpenID = "lark_open_id"
	// FieldYunxiaoUserID holds the string denoting the yunxiao_user_id field in the database.
	FieldYunxiaoUserID = "yunxiao_user_id"
	// FieldGitlabUsername holds the string denoting the gitlab_username field in the database.
	FieldGitlabUsername = "gitlab_username"
	// FieldGitlabEmail holds the string denoting the gitlab_email field in the database.
	FieldGitlabEmail = "gitlab_email"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the user in the database.
	Table = "user"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldLarkUserID,
	FieldLarkUnionID,
	FieldLarkOpenID,
	FieldYunxiaoUserID,
	FieldGitlabUsername,
	FieldGitlabEmail,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLarkUserID orders the results by the lark_user_id field.
func ByLarkUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLarkUserID, opts...).ToFunc()
}

// ByLarkUnionID orders the results by the lark_union_id field.
func ByLarkUnionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLarkUnionID, opts...).ToFunc()
}

// ByLarkOpenID orders the results by the lark_open_id field.
func ByLarkOpenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLarkOpenID, opts...).ToFunc()
}

// ByYunxiaoUserID orders the results by the yunxiao_user_id field.
func ByYunxiaoUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYunxiaoUserID, opts...).ToFunc()
}

// ByGitlabUsername orders the results by the gitlab_username field.
func ByGitlabUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGitlabUsername, opts...).ToFunc()
}

// ByGitlabEmail orders the results by the gitlab_email field.
func ByGitlabEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGitlabEmail, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}
