// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"github.com/liasica/orbit/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// LarkUserID applies equality check predicate on the "lark_user_id" field. It's identical to LarkUserIDEQ.
func LarkUserID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLarkUserID, v))
}

// LarkUnionID applies equality check predicate on the "lark_union_id" field. It's identical to LarkUnionIDEQ.
func LarkUnionID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLarkUnionID, v))
}

// LarkOpenID applies equality check predicate on the "lark_open_id" field. It's identical to LarkOpenIDEQ.
func LarkOpenID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLarkOpenID, v))
}

// YunxiaoUserID applies equality check predicate on the "yunxiao_user_id" field. It's identical to YunxiaoUserIDEQ.
func YunxiaoUserID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldYunxiaoUserID, v))
}

// GitlabUsername applies equality check predicate on the "gitlab_username" field. It's identical to GitlabUsernameEQ.
func GitlabUsername(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGitlabUsername, v))
}

// GitlabEmail applies equality check predicate on the "gitlab_email" field. It's identical to GitlabEmailEQ.
func GitlabEmail(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGitlabEmail, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// LarkUserIDEQ applies the EQ predicate on the "lark_user_id" field.
func LarkUserIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLarkUserID, v))
}

// LarkUserIDNEQ applies the NEQ predicate on the "lark_user_id" field.
func LarkUserIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLarkUserID, v))
}

// LarkUserIDIn applies the In predicate on the "lark_user_id" field.
func LarkUserIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLarkUserID, vs...))
}

// LarkUserIDNotIn applies the NotIn predicate on the "lark_user_id" field.
func LarkUserIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLarkUserID, vs...))
}

// LarkUserIDGT applies the GT predicate on the "lark_user_id" field.
func LarkUserIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLarkUserID, v))
}

// LarkUserIDGTE applies the GTE predicate on the "lark_user_id" field.
func LarkUserIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLarkUserID, v))
}

// LarkUserIDLT applies the LT predicate on the "lark_user_id" field.
func LarkUserIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLarkUserID, v))
}

// LarkUserIDLTE applies the LTE predicate on the "lark_user_id" field.
func LarkUserIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLarkUserID, v))
}

// LarkUserIDContains applies the Contains predicate on the "lark_user_id" field.
func LarkUserIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLarkUserID, v))
}

// LarkUserIDHasPrefix applies the HasPrefix predicate on the "lark_user_id" field.
func LarkUserIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLarkUserID, v))
}

// LarkUserIDHasSuffix applies the HasSuffix predicate on the "lark_user_id" field.
func LarkUserIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLarkUserID, v))
}

// LarkUserIDEqualFold applies the EqualFold predicate on the "lark_user_id" field.
func LarkUserIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLarkUserID, v))
}

// LarkUserIDContainsFold applies the ContainsFold predicate on the "lark_user_id" field.
func LarkUserIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLarkUserID, v))
}

// LarkUnionIDEQ applies the EQ predicate on the "lark_union_id" field.
func LarkUnionIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLarkUnionID, v))
}

// LarkUnionIDNEQ applies the NEQ predicate on the "lark_union_id" field.
func LarkUnionIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLarkUnionID, v))
}

// LarkUnionIDIn applies the In predicate on the "lark_union_id" field.
func LarkUnionIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLarkUnionID, vs...))
}

// LarkUnionIDNotIn applies the NotIn predicate on the "lark_union_id" field.
func LarkUnionIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLarkUnionID, vs...))
}

// LarkUnionIDGT applies the GT predicate on the "lark_union_id" field.
func LarkUnionIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLarkUnionID, v))
}

// LarkUnionIDGTE applies the GTE predicate on the "lark_union_id" field.
func LarkUnionIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLarkUnionID, v))
}

// LarkUnionIDLT applies the LT predicate on the "lark_union_id" field.
func LarkUnionIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLarkUnionID, v))
}

// LarkUnionIDLTE applies the LTE predicate on the "lark_union_id" field.
func LarkUnionIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLarkUnionID, v))
}

// LarkUnionIDContains applies the Contains predicate on the "lark_union_id" field.
func LarkUnionIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLarkUnionID, v))
}

// LarkUnionIDHasPrefix applies the HasPrefix predicate on the "lark_union_id" field.
func LarkUnionIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLarkUnionID, v))
}

// LarkUnionIDHasSuffix applies the HasSuffix predicate on the "lark_union_id" field.
func LarkUnionIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLarkUnionID, v))
}

// LarkUnionIDEqualFold applies the EqualFold predicate on the "lark_union_id" field.
func LarkUnionIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLarkUnionID, v))
}

// LarkUnionIDContainsFold applies the ContainsFold predicate on the "lark_union_id" field.
func LarkUnionIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLarkUnionID, v))
}

// LarkOpenIDEQ applies the EQ predicate on the "lark_open_id" field.
func LarkOpenIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLarkOpenID, v))
}

// LarkOpenIDNEQ applies the NEQ predicate on the "lark_open_id" field.
func LarkOpenIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLarkOpenID, v))
}

// LarkOpenIDIn applies the In predicate on the "lark_open_id" field.
func LarkOpenIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLarkOpenID, vs...))
}

// LarkOpenIDNotIn applies the NotIn predicate on the "lark_open_id" field.
func LarkOpenIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLarkOpenID, vs...))
}

// LarkOpenIDGT applies the GT predicate on the "lark_open_id" field.
func LarkOpenIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLarkOpenID, v))
}

// LarkOpenIDGTE applies the GTE predicate on the "lark_open_id" field.
func LarkOpenIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLarkOpenID, v))
}

// LarkOpenIDLT applies the LT predicate on the "lark_open_id" field.
func LarkOpenIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLarkOpenID, v))
}

// LarkOpenIDLTE applies the LTE predicate on the "lark_open_id" field.
func LarkOpenIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLarkOpenID, v))
}

// LarkOpenIDContains applies the Contains predicate on the "lark_open_id" field.
func LarkOpenIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLarkOpenID, v))
}

// LarkOpenIDHasPrefix applies the HasPrefix predicate on the "lark_open_id" field.
func LarkOpenIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLarkOpenID, v))
}

// LarkOpenIDHasSuffix applies the HasSuffix predicate on the "lark_open_id" field.
func LarkOpenIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLarkOpenID, v))
}

// LarkOpenIDEqualFold applies the EqualFold predicate on the "lark_open_id" field.
func LarkOpenIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLarkOpenID, v))
}

// LarkOpenIDContainsFold applies the ContainsFold predicate on the "lark_open_id" field.
func LarkOpenIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLarkOpenID, v))
}

// YunxiaoUserIDEQ applies the EQ predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDNEQ applies the NEQ predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDIn applies the In predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldYunxiaoUserID, vs...))
}

// YunxiaoUserIDNotIn applies the NotIn predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldYunxiaoUserID, vs...))
}

// YunxiaoUserIDGT applies the GT predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDGTE applies the GTE predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDLT applies the LT predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDLTE applies the LTE predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDContains applies the Contains predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDHasPrefix applies the HasPrefix predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDHasSuffix applies the HasSuffix predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDEqualFold applies the EqualFold predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldYunxiaoUserID, v))
}

// YunxiaoUserIDContainsFold applies the ContainsFold predicate on the "yunxiao_user_id" field.
func YunxiaoUserIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldYunxiaoUserID, v))
}

// GitlabUsernameEQ applies the EQ predicate on the "gitlab_username" field.
func GitlabUsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGitlabUsername, v))
}

// GitlabUsernameNEQ applies the NEQ predicate on the "gitlab_username" field.
func GitlabUsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGitlabUsername, v))
}

// GitlabUsernameIn applies the In predicate on the "gitlab_username" field.
func GitlabUsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldGitlabUsername, vs...))
}

// GitlabUsernameNotIn applies the NotIn predicate on the "gitlab_username" field.
func GitlabUsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGitlabUsername, vs...))
}

// GitlabUsernameGT applies the GT predicate on the "gitlab_username" field.
func GitlabUsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldGitlabUsername, v))
}

// GitlabUsernameGTE applies the GTE predicate on the "gitlab_username" field.
func GitlabUsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGitlabUsername, v))
}

// GitlabUsernameLT applies the LT predicate on the "gitlab_username" field.
func GitlabUsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldGitlabUsername, v))
}

// GitlabUsernameLTE applies the LTE predicate on the "gitlab_username" field.
func GitlabUsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGitlabUsername, v))
}

// GitlabUsernameContains applies the Contains predicate on the "gitlab_username" field.
func GitlabUsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldGitlabUsername, v))
}

// GitlabUsernameHasPrefix applies the HasPrefix predicate on the "gitlab_username" field.
func GitlabUsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldGitlabUsername, v))
}

// GitlabUsernameHasSuffix applies the HasSuffix predicate on the "gitlab_username" field.
func GitlabUsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldGitlabUsername, v))
}

// GitlabUsernameEqualFold applies the EqualFold predicate on the "gitlab_username" field.
func GitlabUsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldGitlabUsername, v))
}

// GitlabUsernameContainsFold applies the ContainsFold predicate on the "gitlab_username" field.
func GitlabUsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldGitlabUsername, v))
}

// GitlabEmailEQ applies the EQ predicate on the "gitlab_email" field.
func GitlabEmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGitlabEmail, v))
}

// GitlabEmailNEQ applies the NEQ predicate on the "gitlab_email" field.
func GitlabEmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGitlabEmail, v))
}

// GitlabEmailIn applies the In predicate on the "gitlab_email" field.
func GitlabEmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldGitlabEmail, vs...))
}

// GitlabEmailNotIn applies the NotIn predicate on the "gitlab_email" field.
func GitlabEmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGitlabEmail, vs...))
}

// GitlabEmailGT applies the GT predicate on the "gitlab_email" field.
func GitlabEmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldGitlabEmail, v))
}

// GitlabEmailGTE applies the GTE predicate on the "gitlab_email" field.
func GitlabEmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGitlabEmail, v))
}

// GitlabEmailLT applies the LT predicate on the "gitlab_email" field.
func GitlabEmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldGitlabEmail, v))
}

// GitlabEmailLTE applies the LTE predicate on the "gitlab_email" field.
func GitlabEmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGitlabEmail, v))
}

// GitlabEmailContains applies the Contains predicate on the "gitlab_email" field.
func GitlabEmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldGitlabEmail, v))
}

// GitlabEmailHasPrefix applies the HasPrefix predicate on the "gitlab_email" field.
func GitlabEmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldGitlabEmail, v))
}

// GitlabEmailHasSuffix applies the HasSuffix predicate on the "gitlab_email" field.
func GitlabEmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldGitlabEmail, v))
}

// GitlabEmailEqualFold applies the EqualFold predicate on the "gitlab_email" field.
func GitlabEmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldGitlabEmail, v))
}

// GitlabEmailContainsFold applies the ContainsFold predicate on the "gitlab_email" field.
func GitlabEmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldGitlabEmail, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
